# Introduction {#introduction .unnumbered}

Founded in 1945, Scholle IPN Corporation (Scholle) is a pioneer in the bag-in-box technology. The company uses to package and dispense a variety of consumer products, from food, beverages to non-food markets such as agricultural chemicals and liquid cleaning products. Scholle mainly produces bag-in-box, pouch packaging, and packaging components like caps, pumps and connectors. Some of Scholle’s competitors in the industry are DuPont Liquid Packaging Systems, Sonoco Products Company and Survitec Group Limited. As a industry-leader, Scholle is constantly providing products in a safe, economic and sustainable way to customers globally.

One of the company’s primary markets is bags for processed-tomato products, such as salsa, tomato paste and ketchup. Every year, the company forecasts the demand for bags for these products, but the accuracy of the prediction is low because the current forecasting methods only considers the quantity of bags shipped in the previous year.

## Problem Statement {problem_statement# .unnumbered}

Scholle needs a more accurate method to forecast its bag shipments. One of the company’s primary markets is packages for processed-tomato products, such as salsa, tomato paste and ketchup. Every year, the company forecasts the demand for bags for these products, but the accuracy of the prediction is low because the current forecasting method only considers the quantity of bags shipped in the previous year. Social media is changing the world. It provides companies with feedback on customer conversations about their products and services, and can affect demand for their products. Currently, this potentially rich data set is not factored in the forecasting of tomato bag shipments. Scholle Management believes there is a relationship between social media feedback and the quantity of tomato bags shipped. Scholle hopes to improve their tomato bag inventory management, level of stock turnover and fulfill the demand more accurately by incorporating these data into their predictive models.

## Research Purpose {research_purpose# .unnumbered}

The purpose of this research is to forecast tomato bag shipments using social media data about certain keywords associated to process tomato products.

Our research objectives include:
* Develop a methodology to determine the positive or negative sentiment associated to a specific product.
* Investigate several data sets to find significant cross-correlation with Scholle data.
* 

## Variables & Scope {variables_scope# .unnumbered}

The key dependent variable we will investigate will be the monthly aggregated shipment quantity of tomato bags. These will be limited to the bags sold in the United States. Our independent variables will be derived from Google Trends and Twitter data generated by users in the United States. 

# Background {#background .unnumbered}

* Social Media is changing the world. It provides companies feedback on customer conversations of their products and services, and can affect demand for their products. Currently, this important metric is not factored in the forecasting of tomato bag sales.

* Scholle Management believes there is a relationship between social media feedback and quantity of tomato bags sold year. Scholle hopes to improve their tomato bag inventory management, level of stock turnover and fulfill the demand more accurately. 

* The project will analyze and provide solutions on how social media conversation correlate with the demand for tomato and factor the findings in the prediction of tomato bag sales.

**Body** 

* Because the sales of tomato bags is depends on  fulfiling the demand by clients which can be affected by Social media conversation, Schoelle must accurately forecast their clients need.   
